//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Государственный_заказ_Челябинской_области.Модели
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int id { get; set; }
        public int Объявитель { get; set; }
        public Nullable<int> Выполнитель { get; set; }
        public string Название_заказа { get; set; }
        public string Описание_заказа { get; set; }
        public string Тип_заказа { get; set; }
        public byte[] Фотография_товара { get; set; }
        public int Цена { get; set; }
        public string Дата_объявления_заказа { get; set; }
        public string Дата_закрытия_заказа { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пользователи Пользователи1 { get; set; }
    }
}
