//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Государственный_заказ_Челябинской_области.Модели
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ПараметрыСоединенияБазыДанных : DbContext
    {
        public ПараметрыСоединенияБазыДанных()
            : base("name=ПараметрыСоединенияБазыДанных")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Договоры> Договоры { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Персонал> Персонал { get; set; }
        public virtual DbSet<Письма_технической_поддержки> Письма_технической_поддержки { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
    }
}
